modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/ChaosAwakens/ChaosAwakens/issues"
license="All Rights Reserved."

[[mods]]
modId="chaosawakens"
version="0.12.1.1"
displayName="Chaos Awakens"
updateJSONURL="https://raw.githubusercontent.com/ChaosAwakens/ChaosAwakens/1.16.5-forge/update.json"
displayURL="https://chaosawakens.github.io/#downloadsDiv"
authors="Chaos Team"
description='''Relive the old Orespawn from 1.7.10 in newer Minecraft versions!'''
logoFile="logo.png"
itemIcon="chaosawakens:royal_guardian_sword"
configBackground="chaosawakens:textures/gui/advancement_bg.png"

# Base
[[dependencies.chaosawakens]]
	modId="forge"
	mandatory=true
	versionRange="[36.2.20,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5,1.17]"
	ordering="NONE"
	side="BOTH"

# Libraries
[[dependencies.chaosawakens]]
	modId="geckolib3"
	mandatory=true
	versionRange="[3.0.94,3.0.98)"
	ordering="NONE"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="patchouli" # Not included for now, will likely be an extra
	mandatory=false
	versionRange="[1.16.4-53,)"
	ordering="AFTER"
	side="BOTH"

# Extras
	# COMMON
[[dependencies.chaosawakens]]
	modId="projecte"
	mandatory=false
	versionRange="[PE1.0,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="jei"
	mandatory=false
	versionRange="[7.7.1.152,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="jeresources"
	mandatory=false
	versionRange="[0.12,]"
	ordering="AFTER"
	side="BOTH"
	
[[dependencies.chaosawakens]]
	modId="jeed"
	mandatory=false
	versionRange="[1.16.5-1.6,]"
	ordering="AFTER"
	side="BOTH"
	
[[dependencies.chaosawakens]]
	modId="theoneprobe"
	mandatory=false
	versionRange="[1.16-3.1.7,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="jade"
	mandatory=false
	versionRange="[2.8.3,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="ironchests"
	mandatory=false
	versionRange="[11.2.21,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="ironshulkerboxes"
	mandatory=false
	versionRange="[5.1.11,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="ironfurnaces"
	mandatory=false
	versionRange="[2.7.7,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="curios"
	mandatory=false
	versionRange="[1.16.5-4.1.0.0,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="travelersbackpack"
	mandatory=false
	versionRange="[5.4.45,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.chaosawakens]]
	modId="datafixerslayer"
	mandatory=false
	versionRange="[1.0-3,]"
	ordering="AFTER"
	side="BOTH"
	
	# CLIENT
[[dependencies.chaosawakens]]
	modId="appleskin"
	mandatory=false
	versionRange="[mc1.16.5-2.4.0,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.chaosawakens]]
	modId="configured"
	mandatory=false
	versionRange="[1.5.3,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.chaosawakens]]
	modId="catalogue"
	mandatory=false
	versionRange="[1.6.1,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.chaosawakens]]
	modId="gamemenumodoption"
	mandatory=false
	versionRange="[1.8.2,]"
	ordering="AFTER"
	side="CLIENT"